#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Ensure script is executed with root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Install HAProxy
apt-get update
apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg
frontend olshea-tech-frontend
        bind *:80
        mode http
        default_backend olshea-tech-backend

backend olshea-tech-backend
        balance roundrobin
        server 442787-web-01 3.84.161.184:80 check
        server 442787-web-02 34.202.233.122:80 check
EOF

# Enable HAProxy init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Testing the HAProxy configuration file
haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart HAProxy service
service haproxy restart
